name: CI

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm
        run: npm install

      - name: Run tests
        run: npm run wdio
        env:
          VERCEL_URL: ${{ vars.VERCEL_URL }}